ALTER TABLE booking_schedules
ADD COLUMN IF NOT EXISTS seat_floor VARCHAR(10) NOT NULL DEFAULT 'any',
ADD COLUMN IF NOT EXISTS seat_window VARCHAR(20) NOT NULL DEFAULT 'any',
ADD COLUMN IF NOT EXISTS priority_top_rows INT NOT NULL DEFAULT 0;
