apiVersion: v1
kind: Service
metadata:
  name: futa-ticket-hunter-api
  namespace: futa
  labels:
    app: futa-ticket-hunter
spec:
  type: ClusterIP
  selector:
    app: futa-ticket-hunter
  ports:
    - name: http
      port: 8080
      targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: futa-ticket-hunter
  namespace: futa
  labels:
    app: futa-ticket-hunter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: futa-ticket-hunter
  template:
    metadata:
      labels:
        app: futa-ticket-hunter
    spec:
      containers:
        - name: api
          image: tuandoquoc/futa-ticket-hunter-api:latest
          imagePullPolicy: Always
          command: ["/app/api", "/app/config.yaml"]
          ports:
            - containerPort: 8080
              name: http
          envFrom:
            - secretRef:
                name: futahunter-secret
          resources:
            requests:
              cpu: "10m"
              memory: "20m"
            limits:
              cpu: "20m"
              memory: "40m"

        - name: worker
          image: tuandoquoc/futa-ticket-hunter-worker:latest
          imagePullPolicy: Always
          command: ["/app/worker", "/app/config.yaml"]
          envFrom:
            - secretRef:
                name: futahunter-secret
          resources:
            requests:
              cpu: "10m"
              memory: "20m"
            limits:
              cpu: "20m"
              memory: "40m"

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: futa-ticket-hunter-ingress
  namespace: futa
  annotations:
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: futa.tuando.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: futa-ticket-hunter-api
                port:
                  number: 8080